name: CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - devel
      - master
      - main

  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

  pull_request_review:
    types:
      - submitted
    status: {}
env:
  RELEASE: release

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v1

      - name: Checkout submodules
        run: |
          echo Checkout submodules
          git submodule sync
          git submodule update --init --recursive

      - name: build
        run: |
          pushd build
          cmake ..
          make -j8
          popd

      - name: test
        run: |
          pushd build
          ./bus_auth
          popd
